entry

Template %{KUBERNETES_API}% name and add service account certs for
downloading static assets directly from api server.

Support installs from kubernetes api server

---

entry

thanks @redref for pointing it out

add args to helm upgrade

---

entry

* Add support for multiple --values files
* Also fix mixed tabs/spaces while we're here.
Related to https://github.com/rancher/rke2/issues/162

Add support for multiple values files in /config

---

Dockerfile.dapper
package/Dockerfile

Keep up to date with Helm v2/v3; use modern golang; move off EOL version
of Alpine.
Related to https://github.com/rancher/helm-controller/issues/65

Update image component versions

---

entry

https://github.com/rancher/rke2/issues/481

Skip helm v2 init if bootstrap env is passed

---

.drone.yml
Dockerfile.dapper
README.md

Signed-off-by: Jacob Blain Christen <jacob@rancher.com>

initial migration from rancher to k3s-io

---

entry

Update stable charts URL

---

entry
package/Dockerfile

Properly quote entrypoint args; update helm versions

---

Dockerfile.dapper
entry
package/Dockerfile

Cleanup and bugfixes for k3s-io/helm-controller#91
* Consistently use double brackets for tests
* Consistently wrap variables in curly braces
* Eliminate unnecessary cut/cat/sed that can be done in pure bash
* Handle pending-upgrade chart status
* Add timeout support; fix whitespace
* Update build image toolchain

Add support for extended install/upgrade timeouts and handle failed/pending states

---

entry

Helm v3 has never supported HELM_TLS_CA_CERT

---

entry

Workaround for:
* k3s-io/k3s#3843

Restart tiller if it crashes

---

entry
package/Dockerfile

This is attempt to handle upgrade failures seen in https://github.com/k3s-io/k3s/issues/3994#issuecomment-919437292

Add mapkubeapis plugin to handle deprecated or deleted APIs

---

package/Dockerfile

Add migration for apiregistration.k8s.io

---

Dockerfile.dapper
entry
package/Dockerfile

Add support for FAILURE_POLICY environment variable

---

package/Dockerfile

Bump Alpine version 3.15.
Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>

Bump Alpine version

---

Dockerfile.dapper
package/Dockerfile

Bump mapkubeapis plugin to released tag v0.3.0

---

Dockerfile.dapper
package/Dockerfile

Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>

Bump Alpine image and Helm version

---

package/Dockerfile

Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>

Bump helm-set-status

---

package/Dockerfile

Pulls in changes from open PR at helm/helm-mapkubeapis#95
Related to: https://github.com/rancher/rancher/issues/40651

Update helm-mapkubeapis plugin

---

.github/dependabot.yml
package/Dockerfile

This contributes to https://github.com/k3s-io/k3s/issues/7040.

Add dependabot to keep dockerfiles up to date

---

entry
package/Dockerfile

Long, long overdue.
Ref: https://helm.sh/blog/helm-v2-deprecation-timeline/

Remove helm v2 support

---

entry

Also handle chart stuck in uninstalling state
* https://github.com/k3s-io/helm-controller/issues/248

Add support for skip-verify/plain-http
