- entry
If default stable helm repo is not available then helm init or installs
will also fail. Test if updating default repos fail and if so remove
stable repo so install from other sources will succeed.
> Support air-gap with helm repos

- entry
https://github.com/rancher/k3s/issues/1299
https://github.com/rancher/k3s/issues/1602
Fix upgrades by removing the version check for existing charts to be able to handle both scenraios:
1- version changed in the helm chart
2- only settings changed in the helm chart
> Dont check for version when upgrading

- package/Dockerfile
This PR is upgrading the version of the Helm binaries included in the current `rancher/klipper-helm:v0.2.5` image respectively to v2.16.7 and v3.2.1.
> Upgrade Helm v2 and v3 binaries

- entry
- For an installed chart, deletion can happen over with name and do not require the repo update.
- This will come handy where for some reason repo update fails while deleting the installed chart.
- fixes https://github.com/rancher/helm-controller/issues/55
> Ignore repo update for chart delete

- entry
Related to: https://github.com/k3s-io/helm-controller/issues/54
If a helm deploy fails, the current klipper-helm image fails to remove the chart and try again.
This can cause issues for use cases where we want to pass in a few helmChart manifests which may have dependency.
When the chart install fails, the actual uninstall fails since we dont really pass the namespace for deleting the chart when using helm3 based deploys
The PR involves using the TARGET_NAMESPACE env variable which is passed by the helmController.
> Uninstall of helm chart fails

- entry
- package/Dockerfile
Fixes CI test failures:
```
helm_v2 init --skip-refresh --client-only
[main] 2021/01/07 23:40:21 Starting Tiller v2.16.10 (tls=false)
[main] 2021/01/07 23:40:21 GRPC listening on 127.0.0.1:44134
[main] 2021/01/07 23:40:21 Probes listening on :44135
[main] 2021/01/07 23:40:21 Storage driver is Secret
[main] 2021/01/07 23:40:21 Max history per release is 0
Creating /root/.helm
Creating /root/.helm/repository
Creating /root/.helm/repository/cache
Creating /root/.helm/repository/local
Creating /root/.helm/plugins
Creating /root/.helm/starters
Creating /root/.helm/cache/archive
Creating /root/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
...
+ helm_v2 repo update --strict …
```
> Update stable repo URL for helm_v2 init

- entry
- package/Dockerfile
Attempt to handle interrupted upgrades by retrying once; stuck install/rollback will be handled as failed and cause an uninstall/reinstall
> Add helm-set-status plugin to handle pending releases

- entry
- package/Dockerfile
klipper-helm does not need to use the root user. In environments where policies prevent root users in containers without necessity, it is difficult to use this image.
> Allow for non-root klipper-helm operation

- entry
When we are in a ipv6-only env, the KUBERNETES_SERVICE_HOST env variable is an ipv6 variable. In that case, we need [ ] to wrap the address.
When that happens, {CHART} needs quotes to avoid bash evaluation. I checked and it does not create a regression with ipv4 addresses
https://github.com/k3s-io/k3s/issues/5237#issuecomment-1075468736 
Signed-off-by: Manuel Buil <mbuil@suse.com>
> Add ipv6 support

- entry
* https://github.com/k3s-io/helm-controller/issues/89
The job fails otherwise with the following:
```
+ helm_v3 repo add x 'https://x'
Error: looks like "https://x" is not a valid chart repository or cannot be reached: Get "https://x/index.yaml": x509: certificate signed by unknown authority
```
> pass --cacert flags to `helm repo` commands too

- entry
In most cases repos are referred with the URL in the helm
install/upgrade/etc, so the install/upgrade commands fail on certificate
errors too.
> keep the --ca-file args in all helm commands

- Dockerfile.dapper
- package/Dockerfile
- scripts/package
Also, inject BUILDDATE as cache-bust to ensure that packages get updated in final stage to address vulns.
> Bump alpine/golang/helm versions

- entry
I ran into an issue with the default "reinstall" failurePolicy when installing [airflow](https://github.com/airflow-helm/charts/tree/airflow-8.2.0/charts/airflow).  The timeout limit was reached during install (because of a slow post-install hook), so `helm uninstall` was triggered.  PVCs were in the "Terminating" state when `helm install` kicked again, and were not created when the released installed the second time around.
This PR adds the `--wait` flag to all `helm uninstall` commands to ensure that resources are deleted before `helm install` runs again.
> Pass --wait flag to `helm uninstall` commands

- entry
Currently, the entrypoint is looking at a Chart's `app_version` to set `INSTALLED_VERSION`, and then checks if that variable is an empty string before uninstalling the chart.
This works well when `appVersion` is defined in `Chart.yaml`, but if not you'll be met with a _"nothing to delete"_ error and the release will not uninstall as expected.  For example:
```
++ helm_v3 ls --all -f '^foo$' --namespace my-namespace --output json
++ tr '[:upper:]' '[:lower:]'
++ jq -r '"\(.[0].app_version),\(.[0].status)"'
+ LINE=,deployed
+ IFS=,
+ read -r INSTALLED_VERSION STATUS _
+ VALUES=
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml'
+ [[ delete = \d\e\l\e\t\e ]]
+ [[ -z '' ]]
+ echo 'No helm_v3 chart installed; nothing to delete'
+ exit …
```
> Use `chart` instead of `app_version` when checking installed version

- entry
This contribution adds an occurence, missed by the original PR that introduced IPv6 (https://github.com/k3s-io/klipper-helm/pull/43). Now, also in the case of reinstalling, the script works as expected in IPv6 environments.
> fix: IPv6 support

- .drone.yml
- Dockerfile.dapper
- package/Dockerfile
Also drop s390x since we no longer have build infra
Ref:
* [Dependency management path traversal](https://github.com/helm/helm/security/advisories/GHSA-v53g-5gjp-272r)
* [Missing YAML Content Leads To Panic](https://github.com/helm/helm/security/advisories/GHSA-r53h-jv2g-vpx6)
> Bump alpine/helmv3

- Dockerfile.dapper
- entry
- package/Dockerfile
Currently the `spec.authSecret` must be a [Basic authentication Secret](https://kubernetes.io/docs/concepts/configuration/secret/#basic-authentication-secret). This adds support for [TLS Secrets](https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets).
* https://github.com/k3s-io/k3s/issues/10124
> Add support for auth via TLS Secret

- package/Dockerfile
* Bump helm v3 to v3.15.3
* Update modules in plugins when building. Most of these plugins don't update often, so they tend to collect stale deps that show up on vuln scans.
* Ref: https://github.com/k3s-io/k3s/issues/10556
> Bump helm version and bump plugin deps when building

- entry
Exiting with a unique code for v2 charts allows us to tell the job to not retry on error using https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-failure-policy
> Exit with unique code for v2 charts

- .drone.yml
- .github/workflows/release.yml
- Dockerfile
- Remove release steps from Drone CI. Note that PR CI still runs there and test builds.
- Arrived at the following setup for CI release:
- All 3 architectures are build in parallel, pushing digest releases to dockerhub and GHCR
- At the end, a merge-manifests job combines them into the actual tagged release and pushed to registries
- amd64 is built on amd64 host
- arm64 is built on arm64 host
- arm32 is emulated on arm64 host (way better performance than emulating on amd64 host)
- `latest` tags are now published. 
- `VERSION-ARCH` tags are no longer published due to limitations on docker push action. So no more `v0.4.10-arm` tag, just the combined tag of `v0.4.10`. 
Note the following must be added before this CI can work
- Action secret `DOCKER_USERNAME` .... user account (for k3s-io …
> Move to Github Actions for Release CI, publish to Dockerhub and GHCR

- .github/workflows/release.yml
Vault login needs the `id-token` permission to run.
> Add missing id-token permission

- Dockerfile
Found this while checking if CVE-2025-32386 is fixed with RKE2's recent stable version 1.32.5 - conclusion: it's not and I think the reason is because its not bumped in k3s/klipper-helm and then dependa-botted to rke2.
Try to contribute/help fixing this :-)
> bump helm CLI binary to version 3.18.1
